"""cria tabela validacao

Revision ID: e5bf44a9f826
Revises: 97672aee94c4
Create Date: 2026-08-13 11:51:06.229398

A décima migração do projeto, e a única da Epic 5 — a tabela que passa a guardar
**tentativa**, e não só entrada (Story 5.6, techspec
`docs/techspec-veredito-e-contador.md`). Uma linha por chamada da rota de
validação, com o evento, quem validou, o veredito e a hora.

Até aqui o banco só sabia de quem entrou: `ingresso.usado_em` e `validado_por`
nascem no caminho do `VALIDO`, e os três vereditos de recusa eram resposta HTTP e
acabavam ali. O motivo inteiro, com a alternativa descartada, está no docstring de
`app/models/validacao.py`.

⚠️ **Ela não é a fonte da verdade sobre quem entrou.** O `entradas` do contador
continua saindo de `ingresso.usado_em`, escrito pelo `UPDATE` condicional do AD-6;
esta tabela é o registro do que foi tentado. Os dois números devem sempre bater, e
um teste confere isso — no dia em que divergirem, é o `usado_em` que ganha.

`String(20)` + `CHECK`, e o `Enum` do Python fora do ORM: a convenção do projeto
desde a Story 1.3, com `usuario.papel` e `reserva.estado` como precedentes. Um
`ENUM` nativo do Postgres exigiria migração de tipo para um quinto veredito.

Índice só em `evento_id`, que é o `where` de toda contagem — **sem composto com
`resultado`**: são quatro valores distintos numa tabela que cresce por show, e o
`GROUP BY` sobre o recorte de um evento já é barato. A disciplina desde a Story
2.3 continua: indexa-se a chave que **é lida**, não todas.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bf44a9f826'
down_revision: Union[str, Sequence[str], None] = '97672aee94c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('portaria_id', sa.Uuid(), nullable=False),
    sa.Column('ingresso_id', sa.Uuid(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    # ⚠️ **Sem `server_default`, ao contrário de `usuario.criado_em`.** O `now()`
    # do Postgres é o instante de início da **transação**, e linhas gravadas na
    # mesma transação sairiam com o carimbo idêntico — uma trilha que não se
    # ordena. Quem escreve é o `_anotar` de `services/ingresso.py`, com o mesmo
    # relógio que grava `ingresso.usado_em`.
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resultado IN ('VALIDO', 'INVALIDO', 'JA_UTILIZADO', 'EVENTO_ERRADO')", name=op.f('ck_validacao_resultado_valido')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_validacao_evento_id_evento')),
    sa.ForeignKeyConstraint(['ingresso_id'], ['ingresso.id'], name=op.f('fk_validacao_ingresso_id_ingresso')),
    sa.ForeignKeyConstraint(['portaria_id'], ['usuario.id'], name=op.f('fk_validacao_portaria_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validacao'))
    )
    op.create_index(op.f('ix_validacao_evento_id'), 'validacao', ['evento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validacao_evento_id'), table_name='validacao')
    op.drop_table('validacao')
    # ### end Alembic commands ###
