"""cria tabela ingresso

Revision ID: e43874e0cf3a
Revises: 6448866ff965
Create Date: 2026-08-12 14:51:12.814506

A sexta migração do projeto, e a última da Epic 3. Com ela o schema passa a ter
sete tabelas: `usuario`, `evento`, `setor`, `evento_portaria`, `reserva`,
`item_reserva` e `ingresso`.

**Nenhuma chave estrangeira leva `CASCADE`, e as três são de propósito.** Aqui
não há o caso que justificou o `CASCADE` de `item_reserva.reserva_id` — item de
checkout some junto com o checkout, mas ingresso pago não some com nada. Apagar
a reserva, o evento ou o setor de um ingresso emitido é recusado pelo Postgres.
Isto estreita mais uma vez o alcance prático do `ON DELETE CASCADE` de `setor`
declarado na `b91316d771ae`: ele já tinha deixado de valer na primeira reserva,
e agora não volta a valer nem depois de a reserva expirar — o ingresso fica.

⚠️ **Sem coluna de unicidade sobre `(reserva_id, setor_id)`**, ao contrário da
`uq_item_reserva_reserva_id_setor_id`. Lá um item por setor é a regra; aqui são
**vários ingressos do mesmo setor na mesma reserva** — um por unidade comprada,
cada um com id e código próprios. É essa multiplicidade que permite validar um
ingresso e o outro não, que é o comportamento inteiro da Epic 5.

⚠️ **Faltam `usado_em` e `validado_por`**, as duas colunas do AD-6, e a falta é
deliberada: validação é a Story 5.2, e a disciplina do projeto é não criar
coluna sem consumidor. A migração que as acrescenta é de lá.

Os dois `op.create_index` são à mão, como sempre — o Postgres não cria índice
para chave estrangeira. `setor_id` fica **sem** índice pelo motivo escrito no
modelo: nenhuma story planejada filtra ingresso por setor.

Ao contrário da `6448866ff965`, esta revisão **não** nasce sem consumidor: a
Story 3.9 emite ingresso na mesma transação em que a reserva vira `PAGA`
(AD-14), e o commit que traz esta migração é o mesmo que traz a emissão.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43874e0cf3a'
down_revision: Union[str, Sequence[str], None] = '6448866ff965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('setor_id', sa.Uuid(), nullable=False),
    sa.Column('titular_nome', sa.String(length=120), nullable=False),
    sa.Column('assinatura', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_ingresso_evento_id_evento')),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], name=op.f('fk_ingresso_reserva_id_reserva')),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], name=op.f('fk_ingresso_setor_id_setor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingresso'))
    )
    op.create_index(op.f('ix_ingresso_evento_id'), 'ingresso', ['evento_id'], unique=False)
    op.create_index(op.f('ix_ingresso_reserva_id'), 'ingresso', ['reserva_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresso_reserva_id'), table_name='ingresso')
    op.drop_index(op.f('ix_ingresso_evento_id'), table_name='ingresso')
    op.drop_table('ingresso')
    # ### end Alembic commands ###
