"""cria tabela evento_portaria

Revision ID: c7cb4a29b7f3
Revises: b91316d771ae
Create Date: 2026-08-11 15:51:40.643771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cb4a29b7f3'
down_revision: Union[str, Sequence[str], None] = 'b91316d771ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_portaria',
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_evento_portaria_evento_id_evento'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_evento_portaria_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('evento_id', 'usuario_id', name=op.f('pk_evento_portaria'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_portaria')
    # ### end Alembic commands ###
