"""cria tabelas reserva e item_reserva

Revision ID: 6448866ff965
Revises: 06c1ad5ac276
Create Date: 2026-08-12 11:51:04.880273

A quinta migração do projeto, e a primeira desde a `06c1ad5ac276` (que ligou a
extensão `unaccent`) que cria tabela. Com ela o schema passa a ter seis:
`usuario`, `evento`, `setor`, `evento_portaria`, `reserva` e `item_reserva`.

**As duas tabelas nascem juntas, numa revisão só, de propósito.** Uma
referencia a outra, e um `downgrade` no meio do caminho deixaria `item_reserva`
apontando para uma tabela que não existe. Por isso `reserva` é criada **antes**
no `upgrade()` e derrubada **depois** no `downgrade()`: ordem trocada quebra a
chave estrangeira.

**Quatro chaves estrangeiras, e só uma leva `CASCADE`.** `item_reserva
.reserva_id` some junto com a reserva, porque item sem reserva não significa
nada. As outras três — `reserva.cliente_id`, `reserva.evento_id` e
`item_reserva.setor_id` — vão **sem `ondelete`**, que é o `RESTRICT` do
Postgres: apagar um show vendido, um setor vendido ou a conta de quem comprou
tem que doer, do mesmo jeito que apagar quem publicou (`evento.organizador_id`)
e quem foi escalado (`evento_portaria.usuario_id`) já dói. A consequência é
assumida: o `ON DELETE CASCADE` de `setor` continua valendo para evento sem
venda e deixa de valer no instante da primeira reserva. Composição some junto;
dinheiro não some.

`estado` é `String(20)` + `CHECK` com a lista literal dos cinco valores do
AD-4, e **não** o tipo `ENUM` nativo — o precedente é o `usuario.papel` da
Story 1.3. Acrescentar um estado aqui é um `DROP`/`CREATE` de constraint que o
`downgrade()` desfaz sem cerimônia; com tipo nativo seria `ALTER TYPE` dentro
de migração, que é o ponto de atrito conhecido daquela escolha.

⚠️ Os três `op.create_index` são à mão, como sempre: o Postgres não cria índice
para chave estrangeira. `reserva.evento_id` fica **sem** índice de propósito —
o motivo está escrito no modelo, e a disciplina desde a Story 2.3 é indexar a
chave que é lida, não todas.

Ao fim desta revisão **nada na aplicação sabe que estas tabelas existem**: não
há rota, service, schema nem tela. Reservar é a Story 3.6. É o mesmo recorte da
`b91316d771ae`, que criou `evento` e `setor` uma epic antes de alguém as ler.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6448866ff965'
down_revision: Union[str, Sequence[str], None] = '06c1ad5ac276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_centavos', sa.BigInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('PENDENTE', 'PAGA', 'RECUSADA', 'EXPIRADA', 'CANCELADA')", name=op.f('ck_reserva_estado_valido')),
    sa.CheckConstraint('total_centavos >= 0', name=op.f('ck_reserva_total_nao_negativo')),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], name=op.f('fk_reserva_cliente_id_usuario')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_reserva_evento_id_evento')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserva'))
    )
    op.create_index(op.f('ix_reserva_cliente_id'), 'reserva', ['cliente_id'], unique=False)
    op.create_table('item_reserva',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('setor_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_centavos', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('preco_unitario_centavos >= 0', name=op.f('ck_item_reserva_preco_nao_negativo')),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_item_reserva_quantidade_positiva')),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], name=op.f('fk_item_reserva_reserva_id_reserva'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], name=op.f('fk_item_reserva_setor_id_setor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_reserva')),
    sa.UniqueConstraint('reserva_id', 'setor_id', name='uq_item_reserva_reserva_id_setor_id')
    )
    op.create_index(op.f('ix_item_reserva_reserva_id'), 'item_reserva', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_item_reserva_setor_id'), 'item_reserva', ['setor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_reserva_setor_id'), table_name='item_reserva')
    op.drop_index(op.f('ix_item_reserva_reserva_id'), table_name='item_reserva')
    op.drop_table('item_reserva')
    op.drop_index(op.f('ix_reserva_cliente_id'), table_name='reserva')
    op.drop_table('reserva')
    # ### end Alembic commands ###
