"""cria tabelas evento e setor

Revision ID: b91316d771ae
Revises: b750db91bf49
Create Date: 2026-08-11 14:34:01.508985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91316d771ae'
down_revision: Union[str, Sequence[str], None] = 'b750db91bf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizador_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('origem_externa_id', sa.String(length=64), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuario.id'], name=op.f('fk_evento_organizador_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento'))
    )
    op.create_table('setor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evento_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('vendidos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('preco_centavos', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('capacidade > 0', name=op.f('ck_setor_capacidade_positiva')),
    sa.CheckConstraint('preco_centavos >= 0', name=op.f('ck_setor_preco_nao_negativo')),
    sa.CheckConstraint('vendidos >= 0 AND vendidos <= capacidade', name=op.f('ck_setor_estoque_valido')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_setor_evento_id_evento'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setor')),
    sa.UniqueConstraint('evento_id', 'nome', name='uq_setor_evento_id_nome')
    )
    # Acrescentado à mão no code review da Epic 2: o Alembic não gera índice
    # para chave estrangeira, e `evento.organizador_id` é a coluna do `where` de
    # toda leitura de "Meus eventos" — o mesmo argumento do `ix_setor_evento_id`
    # logo abaixo. Entrou aqui, e não numa migração nova, porque nesta altura
    # esta revisão só tinha rodado em banco local e de teste; a `main` não
    # conhecia a tabela `evento`. Depois do merge isso não se faz mais.
    op.create_index(
        op.f('ix_evento_organizador_id'), 'evento', ['organizador_id'], unique=False
    )
    op.create_index(op.f('ix_setor_evento_id'), 'setor', ['evento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setor_evento_id'), table_name='setor')
    op.drop_index(op.f('ix_evento_organizador_id'), table_name='evento')
    op.drop_table('setor')
    op.drop_table('evento')
    # ### end Alembic commands ###
