"""acrescenta usado_em e validado_por ao ingresso

Revision ID: 8b97ae6bae09
Revises: e43874e0cf3a
Create Date: 2026-08-12 17:24:59.708635

A sétima migração do projeto, e a primeira da Epic 4. As duas colunas do AD-6
que a `e43874e0cf3a` deixou de fora de propósito entram agora, e não na Story
5.2 como aquele docstring previa — o motivo está na techspec
`docs/techspec-meus-ingressos.md`: o primeiro consumidor é a **leitura**
(`GET /ingressos` separa *Ativos* de *Utilizados* por `usado_em IS NULL`), não
a validação da porta, e adiar as duas deixaria a janela aberta por seis
stories em vez de uma.

`usado_em` é `NULL` para todo ingresso emitido até aqui — a Story 3.9 não
grava a coluna, e não há como ela existir preenchida antes de a 5.2 escrever
nela. `validado_por` referencia `usuario.id` **sem** `ondelete`: apagar uma
conta de portaria que já validou um ingresso é recusado pelo Postgres, o
mesmo tratamento que `reserva.cliente_id` dá a quem comprou.

⚠️ **Sem índice em nenhuma das duas**, ao contrário do costume de indexar toda
chave estrangeira nova. O `UPDATE` da Story 5.2 é `WHERE id = :id AND
usado_em IS NULL` — busca por chave primária —, e o painel da 5.6 filtra por
`evento_id`, que já é indexado. Índice preventivo é peso sem gargalo
demonstrado, a mesma disciplina desde a Story 2.3.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b97ae6bae09'
down_revision: Union[str, Sequence[str], None] = 'e43874e0cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresso', sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingresso', sa.Column('validado_por', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_ingresso_validado_por_usuario'), 'ingresso', 'usuario', ['validado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ingresso_validado_por_usuario'), 'ingresso', type_='foreignkey')
    op.drop_column('ingresso', 'validado_por')
    op.drop_column('ingresso', 'usado_em')
    # ### end Alembic commands ###
