"""acrescenta share_token ao ingresso

Revision ID: ed0bb0dad2a3
Revises: 8b97ae6bae09
Create Date: 2026-08-12 18:24:05.684074

A oitava migração do projeto, e a segunda da Epic 4. Uma coluna só: o endereço
do link compartilhável do ingresso (Story 4.3, techspec
`docs/techspec-link-compartilhado.md`).

`share_token` é `NULL` para todo ingresso emitido até aqui, e continua sendo
`NULL` para quem nunca compartilhou. **`NULL` também é o estado de quem
revogou** (Story 4.4): os dois casos são indistinguíveis de propósito — é o que
faz a revogação ser um corte, e não um aviso de que existiu algo ali.

`String(32)` porque o gerador é o `secrets.token_urlsafe(24)` do
`gerar_share_token()`, o mesmo tamanho do `nonce` e por engenharia igual: 192
bits não se adivinham.

⚠️ **Índice único, e não índice parcial.** No Postgres `NULL` **não colide com
`NULL`** num índice único — milhares de ingressos sem link convivem sem
cláusula `WHERE` nenhuma, e um índice parcial seria complicação sem causa. Ele
não é preventivo: é o `where` exato da rota pública
`GET /ingressos/compartilhados/{token}`, que busca por esta coluna e por mais
nada. A disciplina desde a Story 2.3 continua valendo — indexa-se a chave que
**é lida** num `where`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0bb0dad2a3'
down_revision: Union[str, Sequence[str], None] = '8b97ae6bae09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresso', sa.Column('share_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_ingresso_share_token'), 'ingresso', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingresso_share_token'), table_name='ingresso')
    op.drop_column('ingresso', 'share_token')
    # ### end Alembic commands ###
